version: "3.2"

services:
  api:
    container_name: api
    build: ./api
    environment:
      PG_CONNECTION_STRING: postgres://example:example@store:5432/brittleysen
    ports:
      - 5000:5000
    volumes:
      - ./api/src:/usr/app/api/src

  db:
    container_name: store 
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: brittleysen
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432